# Generated by Django 3.2.7 on 2021-09-17 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tribus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('tribus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Tribus.tribus')),
                ('nuevo_Evento', models.CharField(max_length=100)),
                ('definir_Evento', models.CharField(max_length=200)),
                ('fecha_Evento', models.DateField()),
                ('horas_evento', models.TimeField(blank=True, null=True)),
                ('costo', models.FloatField(default=0)),
                ('añadir_comentarios', models.TextField(max_length=200)),
                ('localizacion_Evento', models.CharField(max_length=200)),
                ('imagen_Evento', models.ImageField(blank=True, null=True, upload_to='')),
                ('archivoInfo', models.FileField(upload_to='')),
            ],
            bases=('Tribus.tribus',),
        ),
    ]
