# Generated by Django 3.2.7 on 2021-10-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tribus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaccion',
            old_name='Accion',
            new_name='accion',
        ),
        migrations.RenameField(
            model_name='reaccion',
            old_name='Imagen',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='reaccionpost',
            old_name='Post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='reaccionpost',
            old_name='Reaccion',
            new_name='reaccion',
        ),
        migrations.RemoveField(
            model_name='reaccionpost',
            name='NumReact',
        ),
    ]
