# Generated by Django 3.2.7 on 2021-10-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tribus', '0002_auto_20211002_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='numDislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='numHates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='numLikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='numLoves',
            field=models.IntegerField(default=0),
        ),
    ]
