# Generated by Django 3.2.7 on 2021-10-06 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tribus', '0002_auto_20210917_0932'),
        ('Tribus', '0003_auto_20211002_1728'),
    ]

    operations = [
    ]
